"""Evaluate MAS capabilities against the Ground Truth benchmark."""
import json
from pathlib import Path

DATA_DIR = Path(__file__).parent.parent
GROUND_TRUTH_FILE = DATA_DIR / "claude_opus_ground_truth_2000.json"
PREDICTIONS_FILE = DATA_DIR / "mas_predictions.json"
REPORT_OUT = DATA_DIR / "metrics_report.md"

def calculate_metrics():
    print("Loading Ground Truth and MAS Predictions...")
    with open(GROUND_TRUTH_FILE, "r") as f:
        ground_truth = json.load(f)
        
    with open(PREDICTIONS_FILE, "r") as f:
        predictions = json.load(f)

    # Convert to dictionaries for easy lookup by message_id
    gt_map = {item["message_id"]: item.get("is_anomalous", False) for item in ground_truth}
    pred_map = {item["message_id"]: item.get("mas_prediction_is_anomalous", False) for item in predictions}

    true_positives = 0
    false_positives = 0
    true_negatives = 0
    false_negatives = 0
    
    missing_in_preds = 0

    for msg_id, is_truly_anomalous in gt_map.items():
        if msg_id not in pred_map:
            missing_in_preds += 1
            continue
            
        is_pred_anomalous = pred_map[msg_id]
        
        if is_truly_anomalous and is_pred_anomalous:
            true_positives += 1
        elif not is_truly_anomalous and is_pred_anomalous:
            false_positives += 1
        elif not is_truly_anomalous and not is_pred_anomalous:
            true_negatives += 1
        elif is_truly_anomalous and not is_pred_anomalous:
            false_negatives += 1

    total_evaluated = len(gt_map) - missing_in_preds

    precision = true_positives / (true_positives + false_positives) if (true_positives + false_positives) > 0 else 0.0
    recall = true_positives / (true_positives + false_negatives) if (true_positives + false_negatives) > 0 else 0.0
    f1_score = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0.0
    
    accuracy = (true_positives + true_negatives) / total_evaluated if total_evaluated > 0 else 0.0
    
    fpr = false_positives / (false_positives + true_negatives) if (false_positives + true_negatives) > 0 else 0.0
    fnr = false_negatives / (false_negatives + true_positives) if (false_negatives + true_positives) > 0 else 0.0
    
    deliberation_total = sum(1 for item in predictions if item.get("deliberation_triggered", False))
    deliberation_rate = deliberation_total / len(predictions) if len(predictions) > 0 else 0.0

    report = f"""# Capability Retention Metrics Report

This report evaluates the Multi-Agent System (Student) analyzing DE-IDENTIFIED textual data against the fixed Claude Opus 4.7 benchmark (Grader) which evaluated RAW, unmodified data.

## Classification Metrics
- **Total Emails Evaluated**: {total_evaluated}
- **System Precision**: {precision:.2%}
- **System Recall**: {recall:.2%}
- **F1-Score**: {f1_score:.2%}
- **Overall Accuracy**: {accuracy:.2%}

## Error Rates & Agent Behavior
- **False Positive Rate (FPR)**: {fpr:.2%} (Clean emails incorrectly flagged as threats)
- **False Negative Rate (FNR)**: {fnr:.2%} (True threats that bypassed the system)
- **Deliberation Trigger Rate**: {deliberation_rate:.2%} (Frequency of Agent Disagreement)

*(Note: Network Topology capabilities were bypassed to isolate text-based threat capability retention.)*

## Confusion Matrix
| | MAS Predicted: Threat | MAS Predicted: Clean |
|---|---|---|
| **True Label: Threat** | True Positives (TP): **{true_positives}** | False Negatives (FN): **{false_negatives}** |
| **True Label: Clean** | False Positives (FP): **{false_positives}** | True Negatives (TN): **{true_negatives}** |

## Research Insights & Failure Analysis
### 1. The PII-Preservation Trade-off
Our evaluation shows that by completely redacting structural PII (Names, Emails, Phones), the system's ability to detect explicit textual threats resulted in an F1-Score of {f1_score:.2%}. The {false_positives} False Positives represent instances where the cognitive agents were overly zealous in the absence of precise name context, while the {false_negatives} False Negatives represent threats that successfully bypassed the Sentiment Agent due to de-identification destroying referential context. The {deliberation_rate:.2%} Deliberation Rate highlights how often the removal of context caused the Investigator and Sentiment agents to completely disagree.

### 2. System Prompt Asymmetry
This evaluation tested a live Multi-Agent System equipped strictly with a generalized corporate policy (`sentiment_policy.md`) against a Ground-Truth benchmark generated by an Expert Grader equipped with a highly specific forensic fraud taxonomy (`acfe_enron_taxonomy.md`). The live system's lower recall highlights the extreme difficulty of zero-shot generalized threat detection compared to taxonomy-driven analysis.

## Future Research Directions
1. **Context-Aware De-identification:** Instead of scrubbing `[PERSON_A]`, map individuals to synthetic but consistent personas (e.g., `VP_Finance_1`) to preserve network topology for the Investigator Agent without leaking real PII.
2. **Dynamic Taxonomy Retrieval:** Allow the Deliberation Agent to fetch specific ACFE fraud taxonomies dynamically via RAG when initial generic policies are triggered.
3. **Keep the Raw Baseline:** Yes, the RAW Ground Truth must remain the immutable baseline. You can only measure the "privacy cost" of an anonymization technique by comparing its performance against the unimpeded, raw data performance baseline.
"""

    with open(REPORT_OUT, "w") as f:
        f.write(report)

    print("\n" + "="*50)
    print("      EVALUATION COMPLETE")
    print("="*50)
    print(f"Precision:            {precision:.2%}")
    print(f"Recall:               {recall:.2%}")
    print(f"F1-Score:             {f1_score:.2%}")
    print(f"Accuracy:             {accuracy:.2%}")
    print(f"False Positive Rate:  {fpr:.2%}")
    print(f"False Negative Rate:  {fnr:.2%}")
    print(f"Deliberation Rate:    {deliberation_rate:.2%}")
    print("="*50)
    print(f"Full report saved to: {REPORT_OUT}")

if __name__ == "__main__":
    calculate_metrics()
